### ISSUE TITLE
Review Lab1 OOP

### ISSUE THREAD

**Issue by Plazmius** [mishadiatel/KPI-labs#2]
Немає перевірки на невід`ємну ініціалізацію рейтингу в конструкторі (більше того, можна зробити ініціалізацію через проперті)

https://github.com/mishadiatel/KPI-labs/blob/ac9831157632fe2d757a50fd115508eb84ccbfd6/3%20semester/OOP/lab%201/Classes/GameAccount.cs#L14

Це краще тримати в класі Game 

https://github.com/mishadiatel/KPI-labs/blob/ac9831157632fe2d757a50fd115508eb84ccbfd6/3%20semester/OOP/lab%201/Classes/Game.cs#L21
повязано з попереднім коментом. gameId має братись з статичного проперті в цьому класі

https://github.com/mishadiatel/KPI-labs/blob/ac9831157632fe2d757a50fd115508eb84ccbfd6/3%20semester/OOP/lab%201/Classes/GameAccount.cs#L28-L29
інкрементувати краще після того як ігри будуть зіграні, адже може статись помилка під час гри

https://github.com/mishadiatel/KPI-labs/blob/ac9831157632fe2d757a50fd115508eb84ccbfd6/3%20semester/OOP/lab%201/Classes/Game.cs#L12

Для цього кращи використати enum, або назвати isWin.
Виправляйте помилки будь-ласка.

**Comment by mishadiatel** [comment]
Виправив

пн, 10 жовт. 2022, 18:39 користувач ArtemMelnychenko <
***@***.***> пише:

**Comment by Plazmius** [comment]
@mishadiatel дякую, роботу зараховано. 

P.S. Одразу не побачив - GameCount проперті зайве. Його можна отримати з historyGames .Count()
